### ISSUE TITLE
Error: background.service_worker is currently disabled

### ISSUE THREAD

**Issue by grimreaper** [molly/courtlistener-download#1]
This extensions seems really useful and would make my life easier. 

Unfortunately, when I tried running it with `web-ext` I get this error:

```
Applying config file: ./package.json
Running web extension from /Users/eax/svn/courtlistener-download
Use --verbose or --devtools to see logging

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/Users/eax/svn/courtlistener-download': Error: background.service_worker is currently disabled
    at RemoteFirefox.installTemporaryAddon (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/firefox/remote.js:92:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FirefoxDesktopExtensionRunner.startFirefoxInstance (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:216:27)
    at async FirefoxDesktopExtensionRunner.run (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:49:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/extension-runners/index.js:66:5)
    at async run (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/cmd/run.js:177:3)
    at async Program.execute (file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/lib/program.js:268:7)
    at async file:///usr/local/Cellar/web-ext/7.11.0/libexec/lib/node_modules/web-ext/bin/web-ext.js:13:1
```

I assume this means its just not compatible with Firefox so that's this feature request.

**Comment by molly** [comment]
I think this should be fixed with 9201efa, but please let me know if you're still having issues!

**Comment by grimreaper** [comment]
this worked to let it run in experimental mode. 
```
diff --git i/manifest.json w/manifest.json
index 12930ce..83780a1 100644
--- i/manifest.json
+++ w/manifest.json
@@ -36,5 +36,11 @@
         "content.js"
       ]
     }
-  ]
-}
\ No newline at end of file
+  ],
+  "browser_specific_settings": {
+  "gecko": {
+    "id": "courtlistener.download@molly.white"
+  }
+}
+
+}
```
is also required to be able to submit the listing to AMO.

I've also taken the liberty to submit this to AMO for you at https://addons.mozilla.org/en-US/firefox/addon/courtlistener-downloader/ (it may not be visible yet)

Please let me know if you don't want that and I'll take down/cancel the listing.

**Comment by molly** [comment]
Thanks. I'd rather submit the extension myself so that I can upload new versions as I develop the extension.

**Comment by grimreaper** [comment]
I disabled it on AMO. you should be able to upload new versions (with a new `id`). 

Thanks for making this.
